version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres001
      POSTGRES_PASSWORD: Am2836
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  webapp:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user_db
      SPRING_DATASOURCE_USERNAME: postgres001
      SPRING_DATASOURCE_PASSWORD: Am2836
    entrypoint: ["./wait-for-postgres.sh", "postgres", "5432", "mvn", "spring-boot:run"]

volumes:
  postgres_data:
