version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres001
      POSTGRES_PASSWORD: Am2836
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d user_db -U postgres001"]
      interval: 10s
      retries: 5


  webapp:
    image: hello-webapp
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8081"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user_db
      SPRING_DATASOURCE_USERNAME: postgres001
      SPRING_DATASOURCE_PASSWORD: Am2836
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
