name: CI with Docker Compose and Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and start containers
      run: docker-compose up -d --build

      
    - name: Run Maven build and generate coverage report
      run: mvn clean verify jacoco:report
    
    - name: List coverage report directory
      run: ls -la ./target/site/jacoco/
    
    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2.3.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./target/site/jacoco/jacoco.xml
