name: CI with Docker, Maven, and Spring Boot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: user_db
          POSTGRES_USER: postgres001
          POSTGRES_PASSWORD: Am2836
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build -t hello-webapp .

    - name: Start the application
      run: |
        docker run -d --name webapp \
          --network container:postgres \
          -e SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/user_db \
          -e SPRING_DATASOURCE_USERNAME=postgres001 \
          -e SPRING_DATASOURCE_PASSWORD=Am2836 \
          -p 8080:8081 hello-webapp

    - name: Wait for the application to be ready
      run: |
        echo "Waiting for webapp to be healthy..."
        until [ "$(docker inspect --format='{{.State.Health.Status}}' webapp)" == "healthy" ]; do
          echo "Current status: $(docker inspect --format='{{.State.Health.Status}}' webapp)"
          sleep 10
        done

    - name: Run tests
      run: mvn clean test

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./target/site/jacoco/jacoco.xml
        flags: unittests
