name: Java CI with Maven and Docker Compose

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      DB_URL: "jdbc:postgresql://localhost:5432/user_db"
      DB_USERNAME: "postgres001"
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build JAR file explicitly
        run: mvn clean package -DskipTests

      - name: Start backend and PostgreSQL explicitly via Docker Compose
        run: |
          docker compose up -d --build
          sleep 30

      - name: Show logs (troubleshooting)
        run: docker compose logs

      - name: Run Tests
        run: mvn clean verify -P skip-e2e-tests

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/site/jacoco/jacoco.xml
          fail_ci_if_error: false  # Explicitly don't fail workflow due to temporary Codecov issues
          verbose: true

