name: CI with Docker Compose and Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and start containers
      run: docker-compose up -d --build

    - name: Monitor and test services
      run: bash ./monitor_and_test.sh

    - name: Run Maven tests
      run: mvn test -Dspring.profiles.active=test

    - name: Shutdown Docker Compose services
      if: always()
      run: docker-compose down
