name: Java CI with Maven and Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Docker Compose Setup (Docker and Compose already available in ubuntu-latest)
      - name: Build and start backend and PostgreSQL via Docker Compose
        run: |
          docker compose up -d --build
          sleep 30  # Increase if necessary, ensure backend is fully ready

      - name: Check backend logs explicitly (troubleshooting)
        run: docker-compose logs

      - name: Run Tests
        run: mvn clean verify

      - name: Generate JaCoCo report
        run: mvn jacoco:report

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/site/jacoco/jacoco.xml
          fail_ci_if_error: true
          verbose: true
